### ISSUE TITLE
[1.18.2] Adding welding recipe causes error "cannot cast IItemStack to ItemStackProvider"

### ISSUE THREAD

**Issue by chemlzh** [Mrthomas20121-Mods/tfctweaker#6]
**[Mod Version]**
Forge: 1.18.2-forge-40.2.4
CraftTweaker: CraftTweaker-forge-1.18.2-9.1.207.jar
TerraFirmaCraft: TerraFirmaCraft-Forge-1.18.2-2.2.21.jar
TFC tweaker: TFCTweaker+1.18.2-0.0.2.jar

**[Bug Description]**
Copy addRecipe line from docs to add welding recipe, save as .zs file, and put it under the script folder

```zenscript
import mods.tfc.WeldingRecipe;

<recipetype:tfc:welding>.addRecipe("welding_test", <item:tfc:metal/ingot/copper>, <item:tfc:metal/double_ingot/copper>, 1, <item:tfc:metal/double_sheet/copper>);
```

Enter the game, type "/reload" and press enter key. Waiting for some time, and CraftTweaker will throw error message.

```
[18:08:11.108][ERROR]: tfc_metallum_create_compact.zs:11:0: tfc_metallum_create_compact.zs:11:0: No matching method found for addRecipe:

Parameter 4: cannot cast IItemStack to ItemStackProvider
```

**Comment by Mrthomas20121** [comment]
that's not a bug. you need to give it an itemStack provider. not an itemstack

**Comment by Mrthomas20121** [comment]
https://docs.blamejared.com/1.18/en/mods/TFCTweaker/Api/Ingredient/ItemStackProvider

**Comment by Mrthomas20121** [comment]
but i see why you were confused, the docs is wrong

**Comment by chemlzh** [comment]
> that's not a bug. you need to give it an itemStack provider. not an itemstack

Then how can I do to convert itemStack to itemStackProvider? Using ItemStackProvider.none(...) ?

**Comment by Mrthomas20121** [comment]
yes 
```zenscript
ItemStackProvider.none(<item:tfc:metal/double_sheet/copper>);
```

**Comment by chemlzh** [comment]
Today I tried the modified welding recipe, and the game threw this error.

![welding_recipe_error](https://github.com/Mrthomas20121-Mods/tfctweaker/assets/32123043/c95ec94c-6bee-470b-96d3-7cbde9478571)

Is there any parameter that I have forgotten to fill in?

**Comment by chemlzh** [comment]
I have found the question: in the newer version of TFC: TNG (for my condition, it's 1.18.2-2.2.21), the welding recipe also has a forging bonus boolean variable called combineForgingBonus.

```java
    public WeldingRecipe(ResourceLocation id, Ingredient firstInput, Ingredient secondInput, int tier, ItemStackProvider output, boolean combineForgingBonus)
    {
        this.id = id;
        this.firstInput = firstInput;
        this.secondInput = secondInput;
        this.tier = tier;
        this.output = output;
        this.combineForgingBonus = combineForgingBonus;
    }
```

And the WeldingRecipe in your TFCTweaker doesn't have this variable, therefore bug has occured.

```java
    public void addRecipe(String name, IIngredient input1, IIngredient input2, int tier, TFCItemStackProvider output) {
        CraftTweakerAPI.apply(new ActionAddRecipe<>(this, new WeldingRecipe(Constants.identifier(name), input1.asVanillaIngredient(), input2.asVanillaIngredient(), tier, output.getInternal())));
    }
```

**Comment by Mrthomas20121** [comment]
i see. will look into it.
