### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by ArikGolub** [Mrthomas20121-Mods/tfctweaker#7]
Maybe I wasn't looking hard enough, but I couldn't find where MetalBuilder saves the models of the items it just created. I want to apply textures, but I can't find the folder where the item models are stored. Or did I have to create them manually? If so, in which folder should I save them?
[1.12.2]

**Comment by Mrthomas20121** [comment]
it doesn't create models. you have to make them yourself. see how tfc does it
